# Generated by Django 4.2.3 on 2024-02-18 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_users_emailfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.course'),
        ),
    ]
