# Generated by Django 4.2.3 on 2024-02-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_users_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='course',
        ),
        migrations.AddField(
            model_name='users',
            name='courses',
            field=models.ManyToManyField(blank=True, to='Account.course'),
        ),
    ]
