# Generated by Django 5.0.4 on 2024-05-29 12:58

import Account.models
import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_coursepurchaserequest_customermessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
        migrations.AlterField(
            model_name='books',
            name='Book_imageUrl',
            field=models.FileField(blank=True, max_length=1000, null=True, storage=Account.models.LocalFileSystemStorage(), upload_to=''),
        ),
    ]
