# Generated by Django 4.2.3 on 2024-02-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_users_image_users_background_imageid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='school_credentials',
        ),
        migrations.RemoveField(
            model_name='users',
            name='school_credentials_three',
        ),
        migrations.RemoveField(
            model_name='users',
            name='school_credentials_two',
        ),
        migrations.AddField(
            model_name='users',
            name='school_credentials_imageId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='school_credentials_imageUrl',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='school_credentials_three_imageId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='school_credentials_three_imageUrl',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='school_credentials_two_imageId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='school_credentials_two_imageUrl',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
