# Generated by Django 4.2.3 on 2024-02-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_users_school_credentials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='imageId',
        ),
        migrations.RemoveField(
            model_name='course',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
