# Generated by Django 5.0.4 on 2024-06-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_post_video_alter_books_book_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='school_credentials_three_imageId',
        ),
        migrations.RemoveField(
            model_name='users',
            name='school_credentials_two_imageId',
        ),
        migrations.AlterField(
            model_name='users',
            name='school_credentials_three_imageUrl',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='school_credentials_two_imageUrl',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
    ]
