# Generated by Django 4.2.3 on 2024-02-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_users_is_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_type',
        ),
    ]
