# Generated by Django 4.2.3 on 2024-02-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_remove_users_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
