# Generated by Django 4.2.3 on 2024-02-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
