# Generated by Django 4.2.3 on 2024-02-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_alter_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='background_imageUrl',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_imageUrl',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
    ]
