# Generated by Django 4.2.3 on 2024-03-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_alter_users_background_imageurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isWebAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
