# Generated by Django 4.2.3 on 2024-03-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0017_users_iswebadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='birthday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='extracurricular',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='mda_imageUrl',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='users',
            name='photo_imageUrl',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='users',
            name='terms_and_agreement_imageUrl',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
    ]
