# Generated by Django 4.2.3 on 2024-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_users_bio_users_birthday_users_extracurricular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo_imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='terms_and_agreement_imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
