# Generated by Django 4.2.3 on 2024-03-09 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0022_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='associated_users',
            field=models.ManyToManyField(blank=True, related_name='associated_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='users',
            name='is_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='my_courses',
            field=models.CharField(choices=[('WebDesign', 'WebDesign'), ('GraphicsDesign', 'GraphicsDesign'), ('UI/UX', 'UI/UX'), ('StoreKeeping', 'StoreKeeping'), ('DigitalExplorer', 'DigitalExplorer'), ('WebDevelopment', 'WebDevelopment'), ('Coding', 'Coding'), ('TradingTitans', 'TradingTitans'), ('PhotoshopProdigy', 'PhotoshopProdigy'), ('CulinaryCanvas', 'CulinaryCanvas'), ('SocialMediaMaverick', 'SocialMediaMaverick'), ('FitProInstructor', 'FitProInstructor'), ('NumberCruncher', 'NumberCruncher'), ('WeddingWizard', 'WeddingWizard'), ('WordPress Wiz', 'WordPress Wiz'), ('Influence Igniter', 'Influence Igniter'), ('Stocks Savvy', 'Stocks Savvy'), ('E-commerce Expertise', 'E-commerce Expertise'), ('Digital Explorer', 'Digital Explorer')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='no_of_notifications',
            field=models.IntegerField(default=0),
        ),
    ]
