export { default as Home } from "./Home";
export { default as HomeCourse } from "./HomeCourse";
export { default as CreatePost } from "./CreatePost";
export { default as CreateCourse } from "./CreateCourse";
export {default as EventsForm } from './Events';
export {default as HomeEvents} from './HomeEvents';
export {default as HomeProfile} from './HomeProfile';
export {default as MyHomeCourse} from './MyHomeCourse';
export {default as HomeTable} from './HomeTable';
export {default as HomeStaff} from './HomeStaff';
export {default as CreateStaff} from './CreateStaff';
export {default as EditCourse} from './EditCourse';
export {default as SingleCourse} from './SingleCourse';
export {default as EditHome} from './EditPost';
export {default as EventsEdits} from './EventsEdit';
export {default as CreateSales} from './CreateSales';
export {default as HomeSales} from './HomeSales';
export {default as CreateBook} from './CreateBooks';
export {default as Books} from './Books';
export {default as MyHomeEvents} from './MyHomeEvents';
export {default as SalesStudentsTable} from './SalesStudentsTable';